services:
  - type: web
    name: lousa-digital
    env: node
    plan: free
    root: .
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SUPABASE_URL
        value: https://pwiefrivtdypnvqzimwv.supabase.co
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: DB_NAME
        value: study_app
      - key: OPENROUTER_API_KEY
        sync: false