services:
  - type: web
    name: backend
    env: python
    plan: free
    root: .
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.server:app --host 0.0.0.0 --port $PORT

  - type: static
    name: frontend
    root: frontend
    buildCommand: yarn install && yarn build
    publishPath: build
